apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo-db:27017"
  MONGO_DB_NAME: "taskdb"
  GITHUB_TOKEN: "Your Github Token"
  GITHUB_REPO: "saurabhk1624/TaskManager"

