apiVersion: v1
kind: Service
metadata:
  name: task-manager-api
  labels:
    app: task-manager-api
spec:
  type: NodePort
  selector:
    app: task-manager-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080

